create table if not exists public.conversation_logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.conversation_logs enable row level security;

grant usage on schema public to anon;
grant insert on table public.conversation_logs to anon;
grant usage, select on sequence public.conversation_logs_id_seq to anon;

create policy "pilot can insert conversation logs"
on public.conversation_logs
for insert
to anon
with check (
  length(session_id) between 1 and 100
  and role in ('user','assistant')
  and length(content) between 1 and 10000
);

-- Intentionally no SELECT/UPDATE/DELETE policy for anon.
-- Pilot visitors can submit logs but cannot read other participants' logs.
